sudo: false
language: node_js
node_js:
  - 'lts/*'
notifications:
  webhooks:
    urls:
      - https://webhooks.tfle.xyz/travis
    on_start: always
cache:
  directories:
    - "node_modules"
install:
  - npm ci
